
server:
  port: 8080
  address: 0.0.0.0

#数据源配置###
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@10.253.96.66:3306/cjwl_wms_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useAffectedRows=true&allowMultiQueries=true
    #url: jdbc:mysql://@10.0.106.34:3306/cjwl_wms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useAffectedRows=true&allowMultiQueries=true
    #哈欧数据源
    #url: jdbc:mysql://@124.70.103.156:8306/hao?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: CjK1rry1as
    #password: Qaz123$%^
    #哈欧数据源密码
    #password: HaohwDB321$
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
#数据源配置###

#mybatis-plus配置###
mybatis-plus:
  global-config:
    db-config:
      id-type: input
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:*/mapper/*.xml
  #mybatis-plus配置###

logging:
  config: classpath:logback.xml
#logging:
# level:
#   com.learn.springmybatis.mapper: debug
#   com.learn.springmybatis.shenzhen.mapper: debug


android:
  version: 1.0.0
  versionName: 1.2.0
  versionCode: 2
  url: https://cjkj-bucket.obs.cn-north-1.myhuaweicloud.com:443/WMS%2Fapp-release.apk
  versionSummary: xxx






